services:
  backend:
    build: ./backend
    container_name: expense-backend
    ports:
      - "8081:8081"
    environment:
      - DB_URL=jdbc:mysql://yamabiko.proxy.rlwy.net:42983/railway?allowPublicKeyRetrieval=true&useSSL=true&connectTimeout=10000&socketTimeout=30000
      - DB_USERNAME=root
      - DB_PASSWORD=aEQWlyFuNDxgGItPixpctIPjIyxSTvYC
    # Đã bỏ depends_on vì dùng DB trên mây

  frontend:
    build:
      context: ./frontend
    container_name: expense-frontend
    ports:
      - "8085:80"
    depends_on:
      - backend
