ALTER TABLE users 
ADD COLUMN dark_mode BOOLEAN DEFAULT FALSE,
ADD COLUMN two_factor BOOLEAN DEFAULT FALSE,
ADD COLUMN email_updates BOOLEAN DEFAULT TRUE,
ADD COLUMN push_notifs BOOLEAN DEFAULT FALSE;
